@startuml
left to right direction

actor "Khách hàng" as KH
actor "Nhân viên" as NV
actor "Quản lý" as QL

rectangle "Website quản lý cửa hàng bánh ngọt" {

  usecase "Đăng ký tài khoản" as UC_Register
  usecase "Đăng nhập" as UC_Login

  usecase "Quản lý khách hàng" as UC_Customer
  usecase "Quản lý sản phẩm" as UC_Product
  usecase "Quản lý nhân viên" as UC_Staff

  usecase "Quản lý đơn hàng" as UC_Order
  usecase "Quản lý hóa đơn" as UC_Invoice

  usecase "Quản lý khuyến mãi" as UC_Promo

  usecase "Báo cáo thống kê" as UC_Report

  usecase "Thêm vào giỏ hàng" as UC_Cart
}

KH --> UC_Register
KH --> UC_Login
KH --> UC_Cart
KH --> UC_Order
KH --> UC_Promo
KH --> UC_Invoice

NV --> UC_Login
NV --> UC_Customer
NV --> UC_Product
NV --> UC_Order
NV --> UC_Invoice

QL --> UC_Login
QL --> UC_Customer
QL --> UC_Product
QL --> UC_Staff
QL --> UC_Order
QL --> UC_Invoice
QL --> UC_Promo
QL --> UC_Report

UC_Cart --> UC_Login : <<include>>

UC_Order --> UC_Login : <<include>>
UC_Order --> UC_Promo : <<include>>
UC_Order --> UC_Invoice : <<include>>

@enduml